### ISSUE TITLE
Broken "paste" symlinks in elementary-xfce-darker

### ISSUE THREAD

**Issue by malysps** [shimmerproject/elementary-xfce#100]
Hello, I've noticed that some icons are wrongly linked in the `/actions/16/` `/actions/22/ ` and `/actions/24/` folders in **elementary-xfce-darker**. These icons are:

edit-paste.png
editpaste.png
gtk-paste.png
stock_paste.png

They should be SVG and they should be linked to SVG, not PNG.

Similarly, stock_paste.png is broken in **elementary-xfce**
Well, these four icons I mentioned above are missing or broken in many places as I go through the "actions" folders.

**Comment by ochosi** [comment]
Thanks for noticing! Should be fixed now.
