### ISSUE TITLE
How to correctly submit pull requests from upstream?

### ISSUE THREAD

**Issue by maeslor** [shimmerproject/elementary-xfce#101]
Hello,

I really appreciate your work and I want to start contributing. I made a fork to upload some new icons from elementary upstream and I wish to submit a propose to be included here, but I don't know whether is better for you to propose directly to the "master" branch, to "working" or to a new one.

Thanks in advance

**Comment by ochosi** [comment]
Hey! Contributions are more than welcome, I'm too busy with upstream Xfce work and Greybird often to pull in all updates from upstream.

You can do pull requests directly to master, that is fine.
The important part to me is that we only carry icons that we have in all sizes and if needed, we add the missing sizes ourselves (which may result in a pull request to upstream).

E.g. the 22px size was dropped upstream and while it's not crucial, I try to include it as some contexts use 22px icons (weird toolbars etc)

**Comment by maeslor** [comment]
Thanks for the feedback.
