### ISSUE TITLE
Wrong network manager icon, when using a vpn

### ISSUE THREAD

**Issue by hannes101** [shimmerproject/elementary-xfce#104]
Hi,
when using a vpn connection the network manager icon indicates that there's no connection, although it works just fine.
Disconnecting from the vpn restores the regular wifi indicator. This happens nm-applet 1.8.2 and the elementary-xfce Darker style.

**Comment by ochosi** [comment]
Could you post a screenshot of the icon or you could also try to determine the icon name with gtkinspector. With what icon theme does it look ok?

**Comment by ochosi** [comment]
Thanks for providing me with the correct icon name. I added icons in all four places where I thought it's necessary - hope I've covered it all.
If you find I've missed something lemme know! (As implied before I don't have a VPN connection ready to reproduce this with)
