### ISSUE TITLE
Icons for supported MATE apps

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/elementary-xfce#105]
With some MATE components potentially being included in Xubuntu 18.04, we might want to put together some new icons or symbolic links for the following applications. If some substantial icon work is needed here, it might be sufficient to just add the symbolic links for early support.

- atril (document viewer, alternative to evince)
- engrampa (archive manager, alternative to file-roller)
- mate-calc (calculator, alternative to gnome-calculator)

**Comment by ochosi** [comment]
I would have preferred a pull-request ;)

**Comment by bluesabre** [comment]
See https://github.com/shimmerproject/elementary-xfce/pull/106

**Comment by ochosi** [comment]
Merged, so I guess this can be closed. Thanks!
