### ISSUE TITLE
elementary-xfce/places/64/distributor-logo-xubuntu.png is 96x96

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/elementary-xfce#109]
While packaging elementary-xfce 0.10...

Creating png icons from svg files and symlinks
** Message: Skipping wip/elementary-xfce/places/64/distributor-logo-xubuntu.png, size too big (96x96 instead of 64x64)

**Comment by ochosi** [comment]
Thanks for reporting, fixed it.
