### ISSUE TITLE
Want to change power manager icon on Arch Xfce Power Manager 1.6.1-1

### ISSUE THREAD

**Issue by ejbolt** [shimmerproject/elementary-xfce#111]
Currently have the icon 'battery-*-symbolic' being used by the newer version of Xfce Power manager.  These are the symbolic icons in elementary-xfce/status/symbolic.  However, I have a friend on Xubuntu that also uses this icon theme, and it uses the battery icons under elementary-xfce/status/32

Now, Ubuntu's 'up-to-date' version of Power Manager is 1.4.1, and when I downgraded to test if this was the issue, the other icons were in face used.  So it's rather an issue with power manager than the icon theme, however, I was wondering if you (or any readers), would know how to rectify/adapt this, so I could use the icons in status/32 instead of symbolic.  I tried replacing those icons but xfce ended up just using _other_ default icons from another theme instead of the ones I copied in.  Would you have any advice?  I'm not terribly well-versed in GTK's settings.

**Comment by ejbolt** [comment]
This is currently the icon shown:![image](https://user-images.githubusercontent.com/21202046/37680232-4a0bd75c-2c51-11e8-91fb-6fb05f86abdc.png)

This is the icon shown by Xubuntu and the one I want to change it to (one of the icons, as it's a set of icons shown based on battery status, but you get the point I think)
![image](https://user-images.githubusercontent.com/21202046/37680340-97480b6c-2c51-11e8-886f-e06c65b6993e.png)

**Comment by ochosi** [comment]
There are probably several ways - all of them would have to be your local modification, I would never merge any of them.

Option 1: delete the relevant symbolic icons from the theme. Ideally the power manager will fall back to colored icons (if everything is correctly implemented).

Option 2: force colored icons by enforcing them in your Gtk theme. Greybird does this in the sidebar style, so you can probably copy-paste that one line from there.

Option 3: you can replace the symbolic icons with colored icons in your theme.

**Comment by ejbolt** [comment]
Thanks will give that a try :)
Wouldn't expect ya to merge, that could break a lot for distros that use older power manager
