### ISSUE TITLE
Tarball releases tagging scheme

### ISSUE THREAD

**Issue by atelszewski** [shimmerproject/elementary-xfce#112]
Hi,

Could you please restore tarball releases tagging scheme to the one that was used with v0.9?
https://github.com/shimmerproject/elementary-xfce/releases/tag/v0.9
https://github.com/shimmerproject/elementary-xfce/archive/v0.9.tar.gz

The new scheme, that is:
https://github.com/shimmerproject/elementary-xfce/releases/tag/elementary-xfce-0.11
https://github.com/shimmerproject/elementary-xfce/archive/elementary-xfce-0.11.tar.gz
causes the downloaded tarball to be named "elementary-xfce-elementary-xfce-0.11.tar.gz"
on browsers that support Content-Disposition header.

Thanks.

--
Best regards,
Andrzej Telszewski

**Comment by ochosi** [comment]
This problem has been previously mentioned in #110 
To be honest there is not much I can do here as I want to continue to follow my Git tagging convention.
