### ISSUE TITLE
Review star are shown incorrectly in gnome-software

### ISSUE THREAD

**Issue by HattinGokbori87** [shimmerproject/elementary-xfce#117]
OS: Ubuntu 18.04
DE: Xfce 4.12
Affected package: gnome-sotware

Review starts are showing incorrectly in gnome-software. Everywhere where there is review stars, all of them are shown as full 5 star(https://imgur.com/a/olQjeaS). This problem happens with the whole "elementary Xfce" icon series including elementary Xfce, elementary Xfce dark, elementary Xfce darker, elementary Xfce darkest. Other icon packs came with Xubuntu 18.04 doesn't create this problem. Ubuntu Studio(which also uses Xfce) also suffers from this problem.

**Comment by ochosi** [comment]
Thanks for reporting this. Do you have any example of icon theme that works ok? (Ideally something other than Adwaita)

**Comment by HattinGokbori87** [comment]
Yes, Gnome, HighContrst, Humanity, Humanity-Dark, LoginIcons, Ubuntu-Mono-Dark, Ubuntu-Mono-Light.

**Comment by ochosi** [comment]
Thanks, found the culprit
