### ISSUE TITLE
build target is run twice

### ISSUE THREAD

**Issue by rscholer** [shimmerproject/elementary-xfce#121]
The build target is run twice when using ```make; make install```.

I'm no expert in Makefiles, but changing of the line:
```install: build``` to ```install:``` fixed the problem with the caveat that ```make install``` no longer implies ```make```.

**Comment by ochosi** [comment]
We'll improve the Makefile, currently it also rebuilds everything everytime and you need to run `make clean` before the next run of `make` (not nice).

**Comment by bluesabre** [comment]
I've made the suggested change after noticing this bug also caused permissions to be replaced when running 'make install'. Thanks!
