### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by subhammridha** [shimmerproject/elementary-xfce#125]
Hi,

Thanks a lot for porting elementary icon set to xfce. But, I am unable to compile and install the icon pack. When I run `make`, it throws the following error:

```sh
gcc -Wall -Werror -O0 -pipe \
svgtopng.c -o svgtopng \
`pkg-config --libs --cflags gtk+-3.0` \
`pkg-config --libs --cflags gdk-pixbuf-2.0`
svgtopng.c: In function ‘svgtopng’:
svgtopng.c:65:3: error: implicit declaration of function ‘strlen’ [-Werror=implicit-function-declaration]
   tmp = g_strndup (src, strlen (src) - 3);
   ^
svgtopng.c:65:25: error: incompatible implicit declaration of built-in function ‘strlen’ [-Werror]
   tmp = g_strndup (src, strlen (src) - 3);
                         ^
cc1: all warnings being treated as errors
make[1]: *** [svgtopng] Error 1
```

Although I do not know much C, if I include `#include <string.h>` in `svgtopng.c`, it successfully compiles and the icon pack can subsequently be installed. Operating system in this computer is CentOS 7.

But later when I tried to compile the icon pack in Fedora, it successfully compiled without any modification.

Why is it that I have to do the above mentioned modification when in CentOS 7. Also, I wish to know whether the modification that I have done is correct or not.

**Comment by ochosi** [comment]
I guess there is no problem with including an additional header in the `svgtopng.c` file. Not sure why string is not part of the default c libs in CentOS...
