### ISSUE TITLE
Unified scheme for git tags

### ISSUE THREAD

**Issue by rscholer** [shimmerproject/elementary-xfce#126]
It would be nice if you could use one scheme for tagging new releases.

It currently fluctuates between: `elementary-xfce-{version}` and `v{version}`.

This has lead me multiple times to adjust my PKGBUILD for Arch Linux (AUR).

**Comment by ochosi** [comment]
Hi, yeah, sorry, I wanted to get the scheme unified for all shimmer projects again (I only deviated with elementary-xfce).
People had some issues with the `elementary-xfce-{version}` scheme (issue #110, issue #112) so I decided to switch back.

I promise I'll try not to change tagging schemes again ;)
