### ISSUE TITLE
More Blue Folders

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/elementary-xfce#127]
I found some additional blue folders after the manila transition. Attached screenshot from Catfish.

add-folder-to-archive
archive-insert-directory
folder-new
folder-copy
folder-move
folder_new
stock_folder-copy
stock_folder-move

![screenshot_2018-09-17_22-46-06](https://user-images.githubusercontent.com/1894517/45661427-7fcbf300-bacb-11e8-824d-9d0a05fb0a24.png)

**Comment by bluesabre** [comment]
Found a few more:

document-open
fileopen
gtk-open

**Comment by zaleksf** [comment]
I really do NOT care for the new tan folder color in version 0.13 from upstream; one of the reasons I previously went with this icon style is that it matched the Greybird theme on XFCE so well with the folders are colored blue.

bluesabre - does your method show how we can select the blue colored folders to replace the tan colored ones? Do I need to make the selection permanent by using the MIME editor? Any additional info you could provide would be great - thanks in advance.

**Comment by ochosi** [comment]
@bluesabre The document-open files and symlinks look ok here. Maybe your thumbnail cache is outdated..?

**Comment by bluesabre** [comment]
@ochosi Everything looks good with the latest commit.
@zaleksf The manila icons are from the upstream elementary icon theme. If you want to continue using the blue icons, feel free to continue using the 0.12.x release.

**Comment by casta** [comment]
Hello, I think there is still one blue folder.
places/mail-sent (seen in evolution)

If you prefer, I can open a new issue to track this last one

Thank’s !

**Comment by ochosi** [comment]
@casta Thanks for noticing, I'm obviously not an evolution user ;)
