### ISSUE TITLE
Pastas Azuis 

### ISSUE THREAD

**Issue by wsalmeida** [shimmerproject/elementary-xfce#128]

**Comment by wsalmeida** [comment]
Achei que não ficou bom a troca das cores das pastas para vanilla.
![deepin screenshot_selecionar area_20180919172455](https://user-images.githubusercontent.com/38542279/45783673-d7d63700-bc3c-11e8-870e-4de20e58cc18.png)

**Comment by ochosi** [comment]
Hi, I don't speak portuguese - please stick to english so everybody can follow.

This change is not unintended, I'm simply following the upstream elementary icon theme (as I do in most choices).
