### ISSUE TITLE
Icon for Bluetooth Manager is incorrect in Xfce's application menu

### ISSUE THREAD

**Issue by Iastonestanding** [shimmerproject/elementary-xfce#129]
Please apply the fix for issue #71 to the 16px variant also. This should fix the icon type and size in the Xfce application menu.

![123](https://user-images.githubusercontent.com/43543071/45955711-e93e8b00-c010-11e8-84ac-aaea409f62c0.png)

Xubuntu 18.10 dev release

**Comment by Mau-G** [comment]
sorry it took so long. Fix merged into master
