### ISSUE TITLE
Different buttons in evince are using the same icon

### ISSUE THREAD

**Issue by ombrophile** [shimmerproject/elementary-xfce#130]
Hello,

Thank you very much for porting the elementary icon set to xfce. 

There is one minute problem though. 

![image](https://user-images.githubusercontent.com/16416796/46070645-f1770180-c19b-11e8-939d-f05017fe5abd.png)

As can be seen in the above image, the **view options** and **file options** menus are using the exact same icons. This same issue was reported earlier here https://github.com/shimmerproject/elementary-xfce/issues/75. But I do not think that it is an evince issue because while using the default icons, or any other icon set for that matter, the two buttons use different icons. This is shown in the following images.

![image](https://user-images.githubusercontent.com/16416796/46072845-01ddab00-c1a1-11e8-9393-f81de74a82e5.png) 
![image](https://user-images.githubusercontent.com/16416796/46086660-3021b180-c1c6-11e8-9446-82cf2f965283.png)

Is there any way the same can be achieved with the present icon set?

Thanks in advance.

P.S. I am using CentOS 7 with xfce and the version of Evince is 3.22.1.

**Comment by skontar** [comment]
"Administration" and "System" in whisker menu in Xfce have the same issue for a while. I have noticed only after changing to a language pack which has these two items next to each other.

**Comment by subhammridha** [comment]
I was comparing the default icons with this icon set. 

In **Action Icons**, I think following are the two icon sets being used by evince to render the two buttons mentioned earlier.
![image](https://user-images.githubusercontent.com/16416796/46257757-88192a80-c4dc-11e8-85dd-331bfb55e19a.png) ![image](https://user-images.githubusercontent.com/16416796/46257771-dc240f00-c4dc-11e8-8ebd-6d4624d4c5c4.png)

 But, in the present icon set, only the following icons are available:

![image](https://user-images.githubusercontent.com/16416796/46257777-17bed900-c4dd-11e8-8b7f-927a7640e269.png)

![image](https://user-images.githubusercontent.com/16416796/46258153-3d4ee100-c4e3-11e8-8047-09466276fc62.png)

I am not sure, but I guess the missing **document-properties-symbolic** icons might be causing evince to use the same icons. Can you please verify whether this is correct or not.

**Comment by subhammridha** [comment]
> "Administration" and "System" in whisker menu in Xfce have the same issue for a while. I have noticed only after changing to a language pack which has these two items next to each other.

I was comparing the **menu icons** categories between Adwaita icon set and the present icon set as well. Following is the list of icons available in the default icon set and the missing icons in the present icon set is marked with a **x**.

>
    applications-accessories                        x
    applications-development
    applications-engineering
    applications-engineering-symbolic
    applications-engineering-symbolic.symbolic      x
    applications-games
    applications-games-symbolic
    applications-games-symbolic.symbolic            x
    appications-graphics
    appications-graphics-symbolic
    appications-graphics-symbolic.symbolic          x
    applications-internet
    applications-multimedia
    applications-multimedia-symbolic
    applications-multimedia-symbolic.symbolic       x
    applications-office
    applications-other
    applications-science
    applications-science-symbolic
    applications-science-symbolic.symbolic          x
    applications-system                             x
    applications-system-symbolic                    x
    applications-system-symbolic.symbolic           x
    applications-utilities
    applications-utilities-symbolic
    applications-utilities-symbolic.symbolic        x
    preferences-desktop
    preferences-desktop-peripherals
    preferences-desktop-personal
    preferences-other
    preferences-other-symbolic
    preferences-other-symbolic.symbolic             x
    preferences-system                              x
    preferences-system-symbolic                     x
    preferences-system-symbolic.symbolic            x
    preferences-system-network
    system-help                                     x
    system-help-symbolic                            x
    system-help-symbolic.symbolic                   x

I think the absence of **preferences-system** and some other icons in the present icon set is the reason for whisker menu to repeat the same icon for the different categories mentioned by you.

**Comment by ochosi** [comment]
Which version of Evince are you using? I have 3.30.1 and I don't see both menu buttons.

Also, open-menu-symbolic.svg and document-properties.svg are indeed different icons in elementary-xfce. (Check elementary-xfce/actions/symbolic/document-properties-symbolic.svg)

**Comment by subhammridha** [comment]
I am using Evince 3.22.1. I rechecked whether the two icons are different or not. But it seems that `document-properties-symbolic.svg` is a symlink of `open-menu-symbolic.svg`. To confirm this, I re-downloaded `elementary-xfce` icon set and I can confirm that the above statement is true in this case as well.

**Comment by skontar** [comment]
It is not an issue on 3.30.2 anymore as they have rearranged the menu / buttons.

**Comment by subhammridha** [comment]
So it seems as 3.30.x has the find button in lieu of the problematic button that I am talking about.

**Comment by philipzae** [comment]
This issue affects Catfish which uses open-menu-symbolic. These images are from xfce-test.

Adwaita  
![image](https://user-images.githubusercontent.com/4412114/107100268-44155d80-682d-11eb-8208-df6ddc646975.png)

Elementary
![image](https://user-images.githubusercontent.com/4412114/107100349-86d73580-682d-11eb-8e54-184424dff7d1.png)

**Comment by ombrophile** [comment]
Closing as the issue I reported is very old and may not be relevant with present versions.

**Comment by philipzae** [comment]
My reply last month is of the latest releases of awaita and elementary.
