### ISSUE TITLE
Inherit elementary icon theme.

### ISSUE THREAD

**Issue by Thyname** [shimmerproject/elementary-xfce#157]
Hi, I see that the index.theme here in github inherits 'Adwaita,hicolor'. I'm using Fedora 30 elementary-xfce-icon-theme-0.13.1-2.fc30 and here it inherits 'Adwaita,gnome,hicolor'. Still it was missing multimedia-photo-viewer icon for elementary-photos 'open with...'.
Just inheriting 'elementary,Adwaita,gnome,hicolor' solves the issue as the icon is present in elementary icon theme.

I don't know if there are issues for you but inheriting 'elementary' in the first place would make you concentrate only on missing xfce stuff.
As an observation, I'm installing Fedora Xfce from netinstall and already I have elementary-code and elementary-photos as they're nice apps and don't have the idiosyncrasies of the current Gnome apps.

**Comment by ochosi** [comment]
The reason for not inheriting elementary originally was that there was no delta between the two. The reason for not making this an add-on is that the focus of elementary changed dramatically and as a single maintainer (luckily getting some help lately) I can't keep up with the pace of upstream. Furthermore, if they add a new icon, they only tend to add it in specific sizes which works fine for their context but not for other DEs.

I guess I can add elementary to the index.theme inherits.

**Comment by Mau-G** [comment]
That would only work if the distro packages the elementary icon set and as packager myself I am not thrilled about creating a "dependency" to another icon theme (exception to Adwaita which is installed almost everywhere by default). I would rather work to sync the missing icons instead directly in elementary-xfce.

**Comment by ochosi** [comment]
Adding something to the inherits has no implications for the dependencies of the icon theme, at least not necessarily. It just means if the elementary theme is installed/available, it will also inherit from there.

The reason why we are lacking some icons, e.g. applications, is that they only exist in few sizes upstream and I don't have time to do the manual scaling.

**Comment by Mau-G** [comment]
> Adding something to the inherits has no implications for the dependencies of the icon theme, at least not necessarily. It just means if the elementary theme is installed/available, it will also inherit from there.

Understood. I mainly meant that I would prefer not to add package dependecy to the elementary theme (for openSUSE) just to complete the set :-). 

> The reason why we are lacking some icons, e.g. applications, is that they only exist in few sizes upstream and I don't have time to do the manual scaling.

Maybe with the help of the communities we can start a list of missing icons.  I don't mind starting working on syncing the icons.
