### ISSUE TITLE
Sound icon doesnt look good in volume control dialog

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#180]
The sound icon on the right side of the dialog seems likes its dimmed with the current greybird theme.
![preview](https://imgur.com/Sh0lnqf.png)

It looks worse with greybird-dark theme.
![preview](https://imgur.com/VrpOask.png)

looks alot better in adwaita theme
![preview](https://imgur.com/yiOVpuo.png)

**Comment by Mau-G** [comment]
Already fixed in master
