### ISSUE TITLE
Software icon not present

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#181]
The software icon is missing from elementary and instead shows an unsuitable fallback icon.
![preview](https://launchpadlibrarian.net/467382484/software%20icon%20in%20menu.png)

The Icon property in the .desktop file is org.gnome.Software

Also reported in launchpad.
https://bugs.launchpad.net/ubuntu/+source/xubuntu-artwork/+bug/1865542

**Comment by Mau-G** [comment]
We could use this icon which is already part of the set and symlink it to org.gnome.Software.svg

https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce/apps/48/softwarecenter.svg

@ochosi any thoughts?

**Comment by philipzae** [comment]
I see this has been broken even as far back as 16.04.

Maybe system-software-installer.svg would be a better one, as its blue rather than purple.
![preview](https://imgur.com/DgCoXZj.png)

**Comment by Mau-G** [comment]
sure but at the same time neither of icons represent very well the "app centre" or "software centre". I'll have a poke around maybe creating one from scratch but the stock one from Gnome isn't all that bad and because it's not a Xfce native program, I wonder how many people actually install it.

**Comment by philipzae** [comment]
The same could be said about apple's app store icon or android's play store icon, atleast the down arrow attempts to symbolize downloading and goes well with the software update icon - system-software-update.svg

The common symbol used for stores is the shopping bag, though I doubt a good one can be done and be clear at 22px used in the whisker menu.

**Comment by Mau-G** [comment]
Elementary upstream uses this one for their app center: 
https://github.com/elementary/icons/blob/master/apps/128/system-software-install.svg

**Comment by philipzae** [comment]
They dont have a 22px version and the 24px version is barely understandable.
https://github.com/elementary/icons/blob/master/apps/24/system-software-install.svg

**Comment by Mau-G** [comment]
> The common symbol used for stores is the shopping bag, though I doubt a good one can be done and be clear at 22px used in the whisker menu.

Whisker menu by default uses 32px so it would be fine. 22px is used by the Application Menu and we can have a different icon for that size. Anyway I'll work a few options

**Comment by philipzae** [comment]
> Whisker menu by default uses ~32px~ 48px [1] so it would be fine. 22px is used by the Application Menu and we can have a different icon for that size. Anyway I'll work a few options

Interesting, as I've never seen a distro using 48px. Yes I guess I wasn't thinking objectively about the 22px, as i was only thinking about Xubuntu which does default to 22px in whisker.

**Comment by ochosi** [comment]
22px ist a rather odd resolution that should die imo.
I would vote for symlinking the existing softwarecenter icon.

If appmenu in Xfce uses 22 by default I'll change that, but I don't think that's the case.

**Comment by Mau-G** [comment]
> 22px ist a rather odd resolution that should die imo.

status notifier and systray default to 22px although I think it should be 16px, especially now that most icons in the set have been “fixed”

> I would vote for symlinking the existing softwarecenter icon.

+ 1 from me at lest till i have time to work on something and make some recommendations.

**Comment by philipzae** [comment]
> +1 from me at lest till i have time to work on something and make some recommendations.

so we should go with softwarecenter.svg, as system-software-update.svg is already used for synaptic and we shouldnt have conflicts.
