### ISSUE TITLE
Blueman and network manager icons not good at 16px

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#185]
In the status notifier panel plugin, i set the max icon to 16px, blueman and network manager icons look like this

![preview](https://imgur.com/0aEWpvv.png)

if i enable symbolic icons, the result is

![preview](https://imgur.com/fHRlXJ1.png)

**Comment by Mau-G** [comment]
it’s already fixed in master branch and we will make a release eventually. there are just other icons to fix first.

**Comment by philipzae** [comment]
okay great. hope it makes it into xubuntu 20.04.

**Comment by Mau-G** [comment]
if you want you can install the set from master so that you can already see the changes and help spot issues ;). instructions are in the readme

**Comment by philipzae** [comment]
Thanks. Did it and will look for new bugs.
