### ISSUE TITLE
Network computer icon seems out of place

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#188]
The icon used for another network computer seems out of place compared to any of the other icons in thunar.
![preview](https://imgur.com/iqRygfa.png)

**Comment by Mau-G** [comment]
yes it's taking it from adwaita apparently... will try to find a more appropriate one

**Comment by philipzae** [comment]
The smaller version looks a bit better
![preview](https://imgur.com/GHF77wZ.png)

**Comment by newhoa** [comment]
Does it need to be a unique icon or should it also use the folder-with-cloud icon?

**Comment by ochosi** [comment]
For starters I think the folder-with-cloud icon would work (aka a symlink)

**Comment by ochosi** [comment]
This one seems to be done
