### ISSUE TITLE
Icon inconsistency on message dialog

### ISSUE THREAD

**Issue by ignaciop** [shimmerproject/elementary-xfce#197]
Hi, I noticed some icon differences between message dialogs on Xubuntu 20.04 daily build. Apparently it uses the same icon but with different style. Here is an example from Thunar (upper left) and Terminal (lower right):

![icns_dialogs](https://user-images.githubusercontent.com/1574316/77259834-fae30c00-6c62-11ea-8887-f89ce105939f.jpg)

Personally, I would prefer the one in Terminal dialog.
Sorry if this is already mentioned or if it goes in the Greybird repo. 

Thank you for your excellent work on Xubuntu and Xfce!

**Comment by ochosi** [comment]
These dialogs are up to the application - as you already noticed.
So feel free to file a bugreport against thunar on bugzilla.xfce.org.
