### ISSUE TITLE
Pidgin no longer has an 'unread message' icon

### ISSUE THREAD

**Issue by jazztickets** [shimmerproject/elementary-xfce#199]
Updated to 0.15 and i'm noticing the icon stays the same:
![bad](https://user-images.githubusercontent.com/425930/77688793-400a8500-6f66-11ea-862b-e513467fc4cf.png)

I'm using the Dark variant.

**Comment by Mau-G** [comment]
looks fine here
![image](https://user-images.githubusercontent.com/44322817/77689606-edb87b00-6fdc-11ea-8c7f-001a85b17243.png)


Could you check that you have the icon: elementary-xfce-dark/panel/16/pidgin-tray-pending.png
