### ISSUE TITLE
inconsistent arrow and home icons in engrampa navigation bar with darker theme

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#203]
![preview](https://launchpadlibrarian.net/473940822/archive%20manager%20toolbar%20icons.png)

![preview](https://launchpadlibrarian.net/473948700/archive%20manager%20toolbar%20icons%202.png)

https://bugs.launchpad.net/ubuntu/+source/xubuntu-artwork/+bug/1872064

**Comment by Mau-G** [comment]
Changing the home icon would break the appearance of the home icon in Thunar side bar. The only solution i can think of that it’s not too intrusive is to make darker use the colored action icons like elementary-xfce and elementary-xfce-dark already does. Basically the same as you see in screenshot #2 with the green arrows etc
