### ISSUE TITLE
16px preferences-other missing

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#204]
Catfish uses the 16px preferences-other icon in its sidebar, but as its not there, the shrunken 24px icon is being used. The simple fix is to create a symlink between it and applications-other under /categories/16/.

![catfish - sidebar other icon](https://user-images.githubusercontent.com/4412114/79031210-3f9cfb80-7bae-11ea-8100-74024adcd4ff.png)

Related bug: https://bugzilla.xfce.org/show_bug.cgi?id=16677

**Comment by Mau-G** [comment]
In my opinion this is not a theme issue. It should be reported against catfish instead and patch it to use applications-other instead.
