### ISSUE TITLE
Software updater icon not clear on white background

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#206]
![preview](https://imgur.com/34wBdvc.png)

**Comment by Mau-G** [comment]
what is the icon size in the screenshot?

**Comment by philipzae** [comment]
I presume its 24px (whisker menu set to smaller) and its also not working correctly at 16px (you cant see it at all).

![preview](https://imgur.com/xjaG2DG.png)

**Comment by Mau-G** [comment]
fixed in commit dd75d87178b16ae68ff9407fffc1849d85e066d7
