### ISSUE TITLE
Missing icons for fileroller and spacefm

### ISSUE THREAD

**Issue by orschiro** [shimmerproject/elementary-xfce#21]
Hi there,

Thanks for providing elementary-xfce. I love the entire iconset!

Two small remarks.

Is it only on my system or are proper icons for fileroller and spacefm yet missing?

This is how they look on my system and you can clearly see that these two icons do not fit to the rest.

![screenshot from 2014-01-16 06 58 26](https://f.cloud.github.com/assets/170947/1928074/43b48592-7e73-11e3-999e-db0deb6efcd5.png)

Thanks for your help!

**Comment by ochosi** [comment]
Closing this as "won't fix", if anybody comes up with a good icon or I suddenly feel inspired and have too much free time, I can re-open this.
