### ISSUE TITLE
Network Manager VPN indicator incorrect color in darker theme

### ISSUE THREAD

**Issue by skontar** [shimmerproject/elementary-xfce#212]
Hi all. I am using the Darker variant of the theme. I see there was a fix for this icon in https://github.com/shimmerproject/elementary-xfce/pull/192 . It seems that the size/color change worked but the VPN indicator is grey instead of expected blue (?) and hard to see.
![elem](https://user-images.githubusercontent.com/10827040/79552010-bcdadb80-809a-11ea-9c55-065a61393673.png)

**Comment by Mau-G** [comment]
Thanks for reporting it. I will see how to fix that. Meanwhile you could also use the status notifier plugin and enable symbolic icons so that the icon in the panel would be monochromatic.

**Comment by ochosi** [comment]
This seems to be long addressed, plus `elementary-xfce-darker` has recently been deprecated.
