### ISSUE TITLE
Gnome Disks icon doesn't look good on white background

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#215]
The icon for Disks (Icon=org.gnome.DiskUtility) doesn't go well with the icon theme and also is doesn't appear well on light on white backgrounds (the one below 'Bluetooth Adapters')
![preview](https://user-images.githubusercontent.com/4412114/79689399-a765dd00-8265-11ea-8503-5d642840d789.png)

![preview](https://imgur.com/DYvzOO7.png)

A simple redirect from /devices/48/drive-harddisk.png would be sufficient to fix this.

**Comment by Mau-G** [comment]
Gnome developers get cranky when we change their icons so i’m reluctant to touch this.

**Comment by philipzae** [comment]
We change the Gnome Software icon, so not sure this is any different.

**Comment by Mau-G** [comment]
Yes and i’m not sure that was the right move

**Comment by ochosi** [comment]
I'm not convinced we should override all Gnome application icons, so closing this for now.
