### ISSUE TITLE
Disable bluetooth icon not visible

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#217]
The white disabled bluetooth icon isn't visible
![image](https://user-images.githubusercontent.com/4412114/87767236-657c1100-c82b-11ea-9406-4f2af72c39e5.png)

until you mouse over the entry
![image](https://user-images.githubusercontent.com/4412114/87767331-8cd2de00-c82b-11ea-98c6-4cb8d5830f28.png)

would suggest having the regular blue bluetooth icon and have a red line through it or have a grayscale version of it.

**Comment by m4u9** [comment]
I am aware.... unfortunately I don't know how to fix it. I think perhaps has to go to blueman upstream
