### ISSUE TITLE
Update for Xfce 4.16 icons

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#220]
Xfce 4.16 brought in new icons with new naming, so this needs to be fixed.
https://wiki.xfce.org/releng/4.16/icons_rdns_naming_for_icons

From Xubuntu 21.04 daily
![image](https://user-images.githubusercontent.com/4412114/104018604-836f7080-51d3-11eb-9856-3e930d4797a8.png)

I would exclude the fixing of the mouse icon, due to issue #214.

**Comment by m4u9** [comment]
We are aware. It will be fixed with symlinks first and some day in the future maybe adapt to the new icons
