### ISSUE TITLE
Low quality search icon in xfce darker

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#223]
Tested in Xfce-Test. See the search icon in the panel.

![image](https://user-images.githubusercontent.com/4412114/105786721-0e53b780-5f97-11eb-9f23-ed69d7174992.png)

![image](https://user-images.githubusercontent.com/4412114/105786761-1f042d80-5f97-11eb-95cd-7942c79511d4.png)

**Comment by ochosi** [comment]
As `elementary-xfce-darker` has been deprecated in v0.17 this is obsolete/fixed.
