### ISSUE TITLE
Blurry document emblem

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#224]
Not sure if this is just my eyes, but the document emblem on the Documents folder seemed blurry to me and the Videos emblem seemed a bit blurry.
![image](https://user-images.githubusercontent.com/4412114/110169673-77d6a980-7e12-11eb-808a-f11121a9b027.png)

**Comment by newhoa** [comment]
The 96px folder/places icons are blurry, you're right. It looks like they were removed with the transition from blue to manilla/tan folders.

Doesn't look too bad on high PPI displays, but does on mid and lower ones. Plus if this theme ends up [supporting HiDPI scaling](https://blog.elementary.io/whats-up-with-hidpi-icons/) , they probably would not scale well.

@ochosi, would it be okay if I add 96px places icons back in (manilla/tan versions)?
