### ISSUE TITLE
Keyboard icon isn't vertically centered

### ISSUE THREAD

**Issue by philipzae** [shimmerproject/elementary-xfce#226]
![image](https://user-images.githubusercontent.com/4412114/110546114-83dea600-8147-11eb-9712-773770377787.png)

Xfce icons
![image](https://user-images.githubusercontent.com/4412114/110546555-1121fa80-8148-11eb-9a55-2a33ef7124b4.png)

**Comment by ochosi** [comment]
The key difference is that the elementary icon theme sports shadows, which suggests that there is gravity etc, so the alignment is versus the bottom, not versus the center (Xfce's upstream icons don't have regular shadows).

So this difference is intentional and fine as is.

**Comment by philipzae** [comment]
So do we have to replace this icon with something else to get a keyboard icon that is centered?

Elementary's current icon is just a single key.
![image](https://user-images.githubusercontent.com/4412114/110585083-b6a98e00-8189-11eb-9469-799203bbbfd2.png)

**Comment by philipzae** [comment]
I checked and Removable Drives and Sound have shadows and are center.

![image](https://user-images.githubusercontent.com/4412114/110660165-b686ae00-81dc-11eb-81e3-c73becba4b73.png)
