### ISSUE TITLE
Change user icon (no criminals)

### ISSUE THREAD

**Issue by Ubuntu-2020** [shimmerproject/elementary-xfce#232]
In **Xubuntu**, by default, the user icon **About Me** looks like a killer wanted notice:
![Xubuntu-User-About-Me](https://user-images.githubusercontent.com/65112331/134176244-0e4bd0fa-dacb-470d-bb2f-9fddad98ac79.gif)

I think it's not right.
Therefore, I ask you to replace the picture about the search for a criminal with a different one.
For example, in **Windows**, by default, **there are no images of criminals**:
![windows-xp-user-accounts](https://user-images.githubusercontent.com/65112331/134176265-abb0e44b-e2c7-4867-84f4-db5aa753a3f1.png)

**Comment by m4u9** [comment]
The icon is from upstream project mugshot. If you want it changed you should open the issue at https://github.com/bluesabre/mugshot

**Comment by Ubuntu-2020** [comment]
**[Thanks](https://github.com/bluesabre/mugshot/issues/18)**.
