### ISSUE TITLE
Remove gnome specific icons

### ISSUE THREAD

**Issue by newhoa** [shimmerproject/elementary-xfce#237]
I'd like to remove the gnome-specific icons but wanted to post an issue here to get feedback.

The theme is filled with `gnome-*` symlinks and while doing updates I spent a lot of time making sure they existed. Edit: While working I've also found there are `redhat-*` icons and a few other odd ones as well that just don't seem to be used or necessary.

But doing some research, it seems they haven't existed in gnome-icon-theme [since Gnome 2.15 in 2006](https://github.com/GNOME/adwaita-icon-theme/commit/1c6b55dd08a725f22a620f00b5e6ac5f3e8b6e45) when they transitioned to the [FreeDesktop Icon Naming Spec](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html). icon-naming-utils [keeps them](https://github.com/Distrotech/icon-naming-utils/blob/master/legacy-icon-mapping.xml) for backward compatibility but it hasn't been updated for 9 years. Elementary upstream [removed them](https://github.com/elementary/icons/commit/25a5852b8b80a9abe1af8078c19e075a4e4f42f5) in 2011.

Anyway, I don't think they're needed anymore. Would it be okay if I removed these?

Thanks.

**Comment by ochosi** [comment]
Sounds good to me!

**Comment by ochosi** [comment]
@newhoa This can be closed now, right?

**Comment by newhoa** [comment]
> @newhoa This can be closed now, right?

Yeah, I'll go ahead and close this one, the 22px icon issue, and the excess dark themes issue. Still some work to do but I just needed the go-ahead to work on them.

Here are some others that I think can be closed:

#216 (replaced with new find icon)
#217 ([Blueman switched to symbolic icons recently](https://github.com/blueman-project/blueman/pull/1725))
#94 (now using unique groovy icon) 
#203 (action arrows now all use the same style)
#193 (Not sure but I think this has been resolved with clipman and power manager updating to symbolic icons)
