### ISSUE TITLE
Remove 22px icons where possible

### ISSUE THREAD

**Issue by newhoa** [shimmerproject/elementary-xfce#238]
22px icons are an unusual size and require any added icon to be created in this size which takes a lot of time and effort. Any future changes in naming conventions will also have to be applied to them. It's a lot of upkeep for a size that may not be used anymore.

Elementary [dropped  22px icons in 2014](https://github.com/elementary/icons/commit/a44bbbc62c259e59d17f911c893f53796bb3637e). So pulling from upstream requires making the missing sized icons.

KDE's Breeze icon theme has 22px icons, but dolphin does variable scaling (I don't know if they still use them in dialogs or toolbars). Are there any places that require 22px icons in Xfce, Gtk, etc?

**Comment by ochosi** [comment]
The only place I surely know uses 22px icons is indicators in the panel. That is due to the fact that Ubuntu hardcoded their Ayatana indicators to a fixed size of 22px.
Other than that I don't think this size has a lot of value, so feel free to clean up.
