### ISSUE TITLE
Stray Icon Prevents gtk-update-icon-cache from Creating a Valid Cache

### ISSUE THREAD

**Issue by jesusofsuburbs** [shimmerproject/elementary-xfce#305]
It seems there's a stray copy of the mousepad icon under apps/32, named "mousepad (copy 1)", that prevents the creation of an icon cache through gtk-update-icon-cache.

**Comment by newhoa** [comment]
Hey, thanks for catching that and reporting! I made a PR for that (#307) so it should be resolved soon.
