### ISSUE TITLE
Make release tarballs more user-friendly/useful

### ISSUE THREAD

**Issue by ochosi** [shimmerproject/elementary-xfce#312]
Currently our release tarballs are not very helpful. Downloading them is the same as checking out the git repository in a certain state.

What would be nice if a GitHub action (triggered on each new tag) would generate a useable tarball, i.e. one in which `make` has already run. I imagine that everything would already be in the right directory structure, ideally even with icon-caches pre-generated so that a user can simply download and untar the archive to their local icon theme directory.
@newhoa thoughts?

**Comment by newhoa** [comment]
This would be nice. I recently tried to build it on KDE and installing the dependencies was a bit of a hassle. I did have to install clang (or would gcc have worked?) which is not listed in the dependencies/install instructions.

I don't know how this would affect distro/repo packagers, though, if they have their own build scripts and are expecting the release as it currently is (although I guess a dual-release would work in that situation?). Might be more of a question for them.

**Comment by newhoa** [comment]
@ochosi I made an issue about supporting HiDPI (#317). The solution requires moving to an SVG-installed theme which might change how to go about doing the Github action and releases. Either the PNG step would need to be optional or it could be eliminated completely.

Not sure if that's the direction you all would like to go in, but in case it is I wanted to put it out there just in case it changed things here.

**Comment by ochosi** [comment]
In theory we could attach a source and a read-for-use tarball.

Adding better hidpi support is definitely something I'd look forward to (even though I don't even have the hardware to test this myself), but let's discuss that in the other issue.
