### ISSUE TITLE
Larger icon for preferences in the menubar

### ISSUE THREAD

**Issue by marko1231991** [shimmerproject/elementary-xfce#319]
slightly larger icon for preferences in the menubar... it's about the version 0.17
![screenshot_2](https://user-images.githubusercontent.com/109438869/179371766-2aa63955-22bb-41a3-b6d6-07dc6fadedd9.png)

**Comment by newhoa** [comment]
@marko1231991 Thanks for reporting! This should be fixed when #331 is merged.
