### ISSUE TITLE
Libreoffice icons in version 0.17

### ISSUE THREAD

**Issue by marko1231991** [shimmerproject/elementary-xfce#320]
In this icon size, just Writer and Calc have a new style with thinner borders.
![screenshot_4](https://user-images.githubusercontent.com/109438869/179372027-92cb1cc6-f210-4e4e-9f35-3b3b7f13f360.png)
In the larger size, all icons have a new style
![screenshot_3](https://user-images.githubusercontent.com/109438869/179372032-85fd94d5-e651-4feb-975f-1665e02339f6.png)
These are of course just well-intentioned suggestions, I love Elementary icons and couldn't even imagine using any others.

**Comment by newhoa** [comment]
@marko1231991 Thanks for the report. They should be updated to match. Currently I'm working on these:

![e-xfce-libreoffice](https://user-images.githubusercontent.com/1984060/183056088-0e8845b6-2d79-437a-9a15-87852e79b9e4.png)

I don't like the Presentation one, and am not sure what to use for Main/Startcenter. The rest seem okay I think? Any feedback would be appreciated. Thanks!

**Comment by marko1231991** [comment]
This [new icon](https://user-images.githubusercontent.com/1984060/183056088-0e8845b6-2d79-437a-9a15-87852e79b9e4.png) for Impress looks more elegant and beautiful. Also, it looks more consistent with other Libreoffice apps icons now. Thank you so much for continuing to improve Elementary icons 👍

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
