### ISSUE TITLE
Session and startup icon

### ISSUE THREAD

**Issue by mare1203** [shimmerproject/elementary-xfce#348]
Hi, I think that the icon for session and startup looks outdated and needs a redesign. 
![image](https://user-images.githubusercontent.com/109438869/194680283-cc7167f1-6173-46d4-9579-b9e2e0aa7172.png)
Maybe it could be replaced with an icon like the one promoted with xfce 4.16:
![image](https://user-images.githubusercontent.com/109438869/194680392-8d7422f5-9836-4471-8d7e-e3828bc9dbc3.png)

**Comment by newhoa** [comment]
Thoughts on a green "start" or "power" icon? Easy to understand? That sort of design would look good at all sizes.

![session-startup-prop](https://user-images.githubusercontent.com/1984060/198245746-432be6bd-2dea-44e4-9a73-170a03e57f56.png)

**Comment by newhoa** [comment]
I went ahead and submitted a PR for review (#349) on this since I had time to work on it and don't know when I might in the future. Feel free to discuss it here or in the PR on whether that's a good solution or not. Thanks.
