### ISSUE TITLE
Missing web app icons

### ISSUE THREAD

**Issue by edmael** [shimmerproject/elementary-xfce#35]
Hi,
elementary-xfce is missing icons for the most used[¹] web apps. The list includes (but is not limited to):
- Gmail
- Google+
- Google Drive
- Google Keep
- Google Maps
- Google Music
- Grooveshark
- Linkedin
- Outlook
- Reddit
- Spotify
- Youtube

I hope that we could see some of those in the future.
Thanks,
Edoardo

[¹]citation needed

**Comment by ochosi** [comment]
For now no further web applications are planned to be added. If anyone wants to contribute more, we can open either separate issues or reopen this one.
