### ISSUE TITLE
Session icons: Base colors on type of action

### ISSUE THREAD

**Issue by newhoa** [shimmerproject/elementary-xfce#351]
I'd like to update these icon colors, as some of them don't match the elementary color palette. But in the process, I'd like them to make a little more sense. A few of them result in destructive actions, but are colored differently (Shutdown and Restart are both destructive but one is a "safe" color and the other "danger"). These should be more consistent.

* Shutdown (Destructive)
* Restart (Destructive)
* Logout (Destructive)
* Lock Screen (Non-Desctructive)
* Switch User (Non-Destructive but session altering)
* Suspend (Non-Destructive but system altering)
* Hibernate (Non-Destructive but system altering)

Destructive: Red
Non-Destructive: Green
System or Session Altering: Orange or Blue? Should `Switch User` and `Suspend/Hibernate` use different colors?

Current:
![current](https://user-images.githubusercontent.com/1984060/198945066-9c617b99-2500-45c4-8c3a-99eb39b0e548.png)

Proposals:

Red, Green, Blue:
![red-green-blue](https://user-images.githubusercontent.com/1984060/198945078-912c3bae-b6ed-4960-b909-ae2d0dc9f23d.png)

Red, Green, Orange:
![red-green-orange](https://user-images.githubusercontent.com/1984060/198945106-aa64182f-30f0-4b5a-be46-461a4260c0fe.png)

Red, Green, Orange, Blue:
![red-green-orange-blue](https://user-images.githubusercontent.com/1984060/198945131-41995aaa-c758-42bc-af0a-b64ee4c72a2e.png)

Any feedback on this would be appreciated!

**Comment by dccoder84** [comment]
[Related](https://github.com/shimmerproject/elementary-xfce/issues/403).
