### ISSUE TITLE
Full trash icon blurry when UI is scaled greater than 1

### ISSUE THREAD

**Issue by dccoder84** [shimmerproject/elementary-xfce#356]
Under the folder elementary-xfce/places/128 there is a user-trash.svg but no user-trash-full.svg. This is in contrast to the lower resolutions like 64 pixels where the icon user-trash-full.svg is available under elementary-xfce/places/64. So can we add an SVG here too?

**Comment by newhoa** [comment]
Hey, thanks for reporting! I made a PR for adding these (#357), so hopefully it'll be fixed in the next update.

**Comment by dccoder84** [comment]
@ochosi When can we have a new release of the elementary-xfce icon theme? The last release was one year ago.

**Comment by ochosi** [comment]
@dccoder84 Sure, I guess we can do a release anytime. I guess I thought people were just using git snapshots (as e.g. Xubuntu does).
@newhoa Anything you'd want to get into the next release or shall I just go ahead and release?

**Comment by newhoa** [comment]
> @dccoder84 Sure, I guess we can do a release anytime. I guess I thought people were just using git snapshots (as e.g. Xubuntu does). @newhoa Anything you'd want to get into the next release or shall I just go ahead and release?

Nah, nothing that can't go in the next release, thanks for asking!

Should Xubuntu be using the git snapshot? That would be nice, but it doesn't seem to currently.

From what I can tell, [the release in the Ubuntu repos](https://packages.ubuntu.com/mantic/elementary-xfce-icon-theme) is the official release (still using 0.17). The git snapshot is in the Xubuntu [Daily PPA](https://launchpad.net/~xubuntu-dev/+archive/ubuntu/ppa) but not in the main repo (also not in the [Xubuntu QA Staging](https://launchpad.net/~xubuntu-dev/+archive/ubuntu/staging)).

Checking it out, the package in the Ubuntu Mantis repos still doesn't have the fix from this issue (user-trash-full at 96px and 128px), but the package in the Daily PPA does.
