### ISSUE TITLE
Missing gtk-copy --> edit-copy symlink

### ISSUE THREAD

**Issue by jesusofsuburbs** [shimmerproject/elementary-xfce#359]
It seems that for the other action icons, there's a missing symlink for gtk-copy pointing to edit-copy, which renders the icons for the copy action in GTK3's context menus as a 'missing icon' icon instead (I use gtk3-classic, rather than upstream gtk3).  The other actions (e.g. gtk-open) do seem to have symlinks installed.  This applies to all icon sizes, from what I can gather.

**Comment by newhoa** [comment]
Thanks for reporting!

That's a simple fix! But while adding the `gtk-copy` symlink, it made me wonder... are these icons ever used beyond menu and button sizes (maybe toolbar)? Wonder if it would be safe to remove 64px and above versions and just keep 48px and below (or maybe 24px and below?).

**Comment by jesusofsuburbs** [comment]
> Thanks for reporting!
> 
> That's a simple fix! But while adding the `gtk-copy` symlink, it made me wonder... are these icons ever used beyond menu and button sizes (maybe toolbar)? Wonder if it would be safe to remove 64px and above versions and just keep 48px and below (or maybe 24px and below?).

Don't quote me on this, but I believe 48px is the largest size used - at least, I could only think of Thunar's file operation dialog, but that's probably using the 48px one.

**Comment by newhoa** [comment]
@jesusofsuburbs Ok thanks! I think that PR should do it so hopefully it'll be in the next release.
