### ISSUE TITLE
Icon open-menu is incorrect at one scale

### ISSUE THREAD

**Issue by caclark** [shimmerproject/elementary-xfce#419]
The open-menu icon at scale /16/ is a gear-wheel. All other icons of this name are 3 horizontal bars.

**Comment by newhoa** [comment]
@caclark, Thanks for the report. I made a [fix here](https://github.com/shimmerproject/elementary-xfce/pull/421/files) if you'd like to check it out and test it. I couldn't actually find an app that uses the plain 16px `open-menu` icon, if you know of one let me know so I can check how it looks in use.

I also upped the contrast a little and the borders should look sharper in dark themes now.

Only issue is I had to make it slightly off center (1px down) to make it look sharp. I tried using thicker lines which made it center, but just looked worse, so hopefully it looks okay slightly off center.

Let me know if that works okay or you think it needs any tweaking.

**Comment by caclark** [comment]
I have attached before and after screenshots of the icon in use.
I noticed the problem when using Geeqie:
https://github.com/BestImageViewer/geeqie

The result is excellent.

Thanks for the work.
![Screenshot_2024-02-10_17-11-43](https://github.com/shimmerproject/elementary-xfce/assets/574981/fa6c2358-be54-4bd4-b801-b5a97a70a718)
![Screenshot_2024-02-10_17-39-40](https://github.com/shimmerproject/elementary-xfce/assets/574981/290af2d4-1ea7-427b-ba67-57e269a40e78)
