### ISSUE TITLE
"software-store" icon needed for Ubuntu App Center / Snap Store

### ISSUE THREAD

**Issue by bluesabre** [shimmerproject/elementary-xfce#420]
We're trialing the new "App Center" (Flutter-based Snap Store) application on Xubuntu 24.04. It's desktop file references an icon named `software-store`. This icon is not installed to hicolor (by nature of snap packages) nor is it included in Adwaita. We should add it to elementary-xfce to better integrate the application.

**Comment by newhoa** [comment]
@bluesabre I think this might be more an upstream issue? The other pre-installed snap apps, Firefox and Firmware Updater, also don't install in hicolor but do still have icons.

Firefox: `/snap/firefox/3687/default256.png`
Firmware Updater: `/snap/firmware/updater/109/meta/gui/icon.png`

Their .desktop files provide absolute paths so they have icons. (looking more into it, this way does seem to be the [Snap desktop icon spec](https://snapcraft.io/docs/desktop-menu-support))

snap-store does [provide an icon](https://github.com/ubuntu/app-center/blob/main/packages/app_center/assets/app-center.png), it just isn't linked in the .desktop file:

`/snap/snap-store/1046/bin/data/flutter_assets/assets/app-center.png`

Although in snap-store (under Manage) they use [this icon](https://git.launchpad.net/snap-store/plain/snap/gui/io.snapcraft.Store.png). This one seems to be provided by [Yaru](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/default/apps/snap-store.svg).

I can report this info upstream if you think that's part of fixing the issue, just let me know.

We can add an icon for a quick fix still, but if users change their icon themes it would go back to not having an icon (without being fixed upstream). Or, another solution, which would work across all themes, could be to provide and install the icon in xubuntu-default-settings to hicolor if that's possible?
