### ISSUE TITLE
missing icons under action buttons panel item

### ISSUE THREAD

**Issue by dmillfree868** [shimmerproject/elementary-xfce#450]
When you choose the actions of restart, shutdown, or log out and you get that small window with the 30 second timer, in each case the window title bar icon is missing.

**Comment by newhoa** [comment]
Thanks for the report, but the icon is missing no matter the icon theme. It's also the same in some panel dialogs (like when you try to remove a plugin via right click) but not others (Status Tray Items > Clear Known Items). So this seems to be an issue with those plugins, which are part of xfce4-panel.

Looking at the source code of xfce4-panel, I think probably the gtk window icon needs to be set. But it would probably be better to use libxfce4ui as some plugins do, that way all dialogs have the same icons and layout (the ones that use libxfce4ui do not have this issue).

I'm going to go ahead and close this. If you'd like to report it on the [xfce4-panel issue tracker](https://gitlab.xfce.org/xfce/xfce4-panel) feel free. I'll try to make a PR/fix for it there when I can.

**Comment by newhoa** [comment]
Reported upstream [here](https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/835).
