### ISSUE TITLE
Incorrect icon for .iso file

### ISSUE THREAD

**Issue by ignaciop** [shimmerproject/elementary-xfce#495]
Hi @newhoa! First, thank you for your work in these icons!

There is a bug in the last release (0.20), precisely in the .iso image files icon

![Captura de pantalla_2024-10-11_23-31-39](https://github.com/user-attachments/assets/8b753842-7110-4bfa-9012-1b7e4befc0fd)

It shows application-x-generic.svg but should be application-vnd.efi.iso

Thank you!

**Comment by newhoa** [comment]
You're welcome and thanks for the report!

An icon for `application-vnd.efi.iso` [does exist](https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce/mimetypes/48/application-vnd.efi.iso.svg) in 0.20 so I wonder what's going on. It does work for me (using Thunar 4.19.3 and `shared-mime-info` 2.4) so unfortunately I can't reproduce this.

Could you let me know the file manager you're using and its version, your distro and version, and the version of `shared-mime-info` you're using?

Other things maybe (you may have already tried these but worth mentioning)... some file managers don't refresh all icons when switching themes so try refreshing or logging out and back in. There could be conflicting versions of `elementary-xfce` installed. Try checking `/usr/share/icons`, `/usr/local/share/icons/`, `~/.local/share/icons`, and `~/.icons` to make sure there are no duplicated themes installed.

Thanks.

**Comment by ignaciop** [comment]
I tried logging out but it did not work. I checked for conflicting versions, but it seems ok (installed globally in /usr/share/icons) I'm on Debian 12.7 stable, Thunar 4.18.4 and shared-mime-info 2.2
Thanks again for your help!

**Comment by newhoa** [comment]
> I tried logging out but it did not work. I checked for conflicting versions, but it seems ok (installed globally in /usr/share/icons) I'm on Debian 12.7 stable, Thunar 4.18.4 and shared-mime-info 2.2 Thanks again for your help!
> 
> I also tried in another Debian stable and the same thing happened; but in Debian Sid, Thunar 4.18.11 and shared-mime-info 2.4 works correctly...

Thanks for all the info! It looks like shared-mime-info 2.2 [still uses](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/2.2/data/freedesktop.org.xml.in?ref_type=tags#L1697) `application-x-cd-image` and [it was changed](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/commit/35054978161faf8f39720a15a98080e5d800898a) to `application/vnd.efi.iso` in 2.3/2.4.

So you could try making a link `application-x-cd-image` to 'application/vnd.efi.iso' or upgrade to `shared-mime-info` 2.4. See if one of those helps.

elementary-xfce 0.20 uses shared-mime-info 2.4 names so I think one of those should help. Wonder if we should make a certain version shared-mime-info a requirement when doing releases.

**Comment by ignaciop** [comment]
> 
So you could try making a link application-x-cd-image to application/vnd.efi.iso or upgrade to shared-mime-info 2.4. See if one of those helps.
> 

I will try that. Thanks @newhoa !
