### ISSUE TITLE
Different categories icons size missing

### ISSUE THREAD

**Issue by sergiobenrocha2** [shimmerproject/elementary-xfce#62]
There are some categories icons that are missing in others sizes as 64 px or 128 px, you can see when you change size in whisker menu. I'm working in it (just to add this to milestone so i don't forget :)  ).

**Comment by sergiobenrocha2** [comment]
Missing yet:

```
16:
  -- applications-education.svg

24:
  -- applications-games.svg
  -- applications-education.svg

32:
  -- applications-games.svg
  -- applications-education.svg

64:
  -- applications-games.svg
  -- applications-education.svg

96:
  -- applications-development.svg
  -- ../../actions/128/document-properties.svg (applications-system.svg)
  -- ../../apps/48/gnome-desktop-config.svg (preferences-desktop.svg)
  -- applications-games.svg
  -- applications-education.svg

128:
  -- applications-science.svg
  -- applications-games.svg
  -- applications-education.svg
```

**Comment by newhoa** [comment]
Kind of addressed this one over time in various PRs/commits (but esp with https://github.com/shimmerproject/elementary-xfce/commit/3dc3e80e74ab159be8bda5ad650b471864a2f433). Should be all fixed and uniform in current git (save for `gtk-preferences` which shouldn't be needed above 32px).

Feel free to re-open or msg if there are any other issues here!
