### ISSUE TITLE
News mimes icons and clean-up

### ISSUE THREAD

**Issue by sergiobenrocha2** [shimmerproject/elementary-xfce#63]
Working in that. Some mimes are missing or they have that old sheed style, like lua, perl, C#, C++...

Probably i will make new mimes to lua (already), perl and php. Others, i think it's better to symlink to text-x-script, at least until someone think in better icon to represent them.

This is what i have for Lua:

http://www.zimagez.com/galerie/Lua-Mimes-32287-0.php

**Comment by ochosi** [comment]
This is pretty much covered by v0.16 and v0.17.
