### ISSUE TITLE
Icon for Bluetooth Manager is Incorrect in Current Build on Launchpad

### ISSUE THREAD

**Issue by bongochong** [shimmerproject/elementary-xfce#71]
It's far too small and nothing like the original:
![screenshot - 12262014 - 05 55 32 pm](https://cloud.githubusercontent.com/assets/10101120/5559769/687c4d28-8d28-11e4-945b-ea5a3032320c.png)

P.S. Package is 201412151131~ubuntu14.04.1

**Comment by ochosi** [comment]
Thanks, I'll take a look.

**Comment by ochosi** [comment]
Should be fixed, re-open or comment if not.
