### ISSUE TITLE
Panel icons not displayed correctly 

### ISSUE THREAD

**Issue by Milozzy** [shimmerproject/elementary-xfce#72]
Hi guys.
I will use a couple of screenshot for explaining the problem because I am not sure how to put it in words.

When I login on my Xfce desktop, my panel icons are like this:

![istantanea - 12022015 - 10 29 41](https://cloud.githubusercontent.com/assets/864646/6164796/b3c9506a-b2a2-11e4-870d-9268d32d3efd.png)

As you can see, mailwatch plugin uses the ugly default icon and the volume-mixer icon does not scale correctly. Not in the screenshot, but clipman plugin as the same problem of the mixex, the icon does not scale correctly.

If I open my panel properties and change the panel size from 26 to 27 and then back to 26... magic!
This is the result:

![istantanea - 12022015 - 10 37 10](https://cloud.githubusercontent.com/assets/864646/6164822/1ed59ddc-b2a3-11e4-87be-1b0e1fdba23c.png)

Clipman, mailwatch, volume mixer... all of them are perfect!

I try a lot of thing, using the iconset package in the repo, pulling from git, deleting the icon-them cache, regenerating it... nothing.

My system is Fedora 21.

Thank you!!

**Comment by ochosi** [comment]
For Xubuntu I converted the icon-theme to png, that usually helps. (You can either check the script in debian/control in xubuntu-artwork or just pull the xubuntu-artwork package from launchpad.)

**Comment by ochosi** [comment]
By the way, do you use separators to get the padding between the items? :)

**Comment by Milozzy** [comment]
@ochosi oh nice to know! I will get the archive from launchpad and try! If the issue is known, can I ask you why you don't use png upstream too? Just curious ;)

Yep, every item is between separators... Sexy uh? :D
I only wish a could set the spacing between items in the notification area too :)

Thanks Simon!

**Comment by ochosi** [comment]
For maintenance png icons suck, svg can be edited nicely, so that's the main reason I stick to svg only here.

Hehe, thought so ;)
Yeah, I've considered working on being able to insert padding in the systray, but then again there are always 1000 things to do and this wasn't a top priority.

**Comment by Milozzy** [comment]
I put the png from the xubuntu-artwork package in my system, but doesn't seem to help :(

**Comment by ochosi** [comment]
I presume you removed the other icon-theme or overwrote it somehow to make sure you're using the pngs?
Also, gtk-update-icon-cache -f might help.

**Comment by Milozzy** [comment]
You presume well, but I miss the cache update step... will try! Thanks!!!

**Comment by ochosi** [comment]
Not really an icon theme issue, closing.
