### ISSUE TITLE
Evince uses two similar icons

### ISSUE THREAD

**Issue by haarp** [shimmerproject/elementary-xfce#75]
Evince has two icons in the toolbar. one is document properties (on the left here) and the other the main menu. Both icons however look very similar:

http://i.imgur.com/W3OPcu3.png

That's rather confusing. I never know which one to press. Can this icon set do something about this? I realize that Evince is not exactly an Xfce application, but this is on an Xfce DE.

(I think it would actually be nice if the menu icon used the modern hamburger-style)

**Comment by ochosi** [comment]
Looks like you're using a modified version of Evince. What version of Evince are you using and what distro?

Anyway, all in all, I can't do much about this. It's up to the developers to define the icons in their UI...

**Comment by haarp** [comment]
This is Evince 3.12.2 on Gentoo. The only modification I made is to retain the titlebar when maximized. I refuse to upgrade it tho, because I really dislike what Gnome has done to it.

**Comment by ochosi** [comment]
Right, that's totally up to you what Evince version you use. As I said, the UI would have to be fixed, I'm not even sure what those two buttons are supposed to do...
