### ISSUE TITLE
Wi-fi connected notification icon is ugly in elementary-xfce-darkest

### ISSUE THREAD

**Issue by Yanpas** [shimmerproject/elementary-xfce#78]
It should be " 3 blue waves" like in other themes.
![screenshot - 27 03 2015 - 02 17 54](https://cloud.githubusercontent.com/assets/7345761/6859259/f6429fd6-d427-11e4-852e-8d51fad3e60a.png)

**Comment by ochosi** [comment]
What "other themes" are you referring to? Do you mean it works fine in elementary-xfce or elementary-xfce-dark?

Generally speaking elementary-xfce-darkest inherits all icons from elementary-xfce (apart from the ones in the action context), so I don't see any reason why it should behave any different from the parent theme.
That said, I never see this notification so I can't reproduce your problem.

**Comment by Yanpas** [comment]
elementary-xfce and elementary-xfce-darkest icons differs from elementary-dark and elementary-darker. Well, it is normal behavior for tray icons, but in this case these 4 themes should use the same icon.
elementary-xfce and elementary-xfce-darkest icons are low relolution
![screenshot - 27 03 2015 - 11 36 25](https://cloud.githubusercontent.com/assets/7345761/6864917/f1e65c88-d478-11e4-8308-0603b411903d.png)
![screenshot - 27 03 2015 - 11 55 56](https://cloud.githubusercontent.com/assets/7345761/6864918/f1ebb1a6-d478-11e4-91a7-38de109c8c24.png)

**Comment by ochosi** [comment]
Ok, found the problem and fixed it. Thanks!
