### ISSUE TITLE
No network icon for elementary-darker with the panel size 18 and lower

### ISSUE THREAD

**Issue by Yanpas** [shimmerproject/elementary-xfce#81]
Screenshot. The nm-applet uses golden icon with two cables
![_2015-04-04_14-47-38](https://cloud.githubusercontent.com/assets/7345761/6992482/03556e2a-dada-11e4-9016-dd9c2255da40.png)

**Comment by ochosi** [comment]
The problem with 16px icons is that they usually appear in different contexts than panels, e.g. menus.
As nm-applet still isn't using symbolic icons (which would be recolored correctly irrespective of context) there's nothing I can do without compromising the icon's use in another context. Sorry.
