### ISSUE TITLE
xfce4-power-manager-1.5 uses dark icon on dark panel

### ISSUE THREAD

**Issue by haarp** [shimmerproject/elementary-xfce#82]
I'm using a dark panel with elementary-xfce-darker. Before xfce-power-manager-1.5, the correct white icon was used. After the upgrade, it insists on using the dark one, which looks terrible on the dark panel.

**Comment by ochosi** [comment]
That's a bug in the power manager that has been fixed in git master already and will be shortly released with 1.5.1.
