### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by hobarrera** [shimmerproject/elementary-xfce#88]
I'm interested in reusing some icons, but there seems to be no `LICENCE` file. What's the licence for these icons?

**Comment by hannes101** [comment]
Since it's a fork of https://launchpad.net/elementaryicons I think it should also be GPLv3. But true, there should be a license file.

**Comment by hobarrera** [comment]
Sorry, I sent the PR (mostly to get this out of the way quickly) before your edit.

[Upstream](https://launchpad.net/elementaryicons) seems to be using GPLv3 though. Hasn't there been any recent pull from there? If so, GPLv3 would apply.

**Comment by ochosi** [comment]
Yes, at some point upstream changed their license. I will ask and check why and I guess ultimately move to GPL3 too.

**Comment by ochosi** [comment]
Actually the GPL2 version is totally fine (even if upstream uses GPL3 and I merge stuff from there) as the GPL2 I'm using has the "any later version" clause:
https://github.com/shimmerproject/elementary-xfce/blob/master/elementary-xfce/LICENSE#L296

For why this is ok, read here: http://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility

**Comment by Foggalong** [comment]
That's not actually part of the license terms, just the instructions for application. I believe you have to actually specify somewhere that you're making use of the "version 2 or later" clause either in the LICENSE or somewhere in the codebase (like the README)

**Comment by ochosi** [comment]
Should be dealt with now, updated all AUTHORS files.

**Comment by Foggalong** [comment]
Awesome :+1:
