### ISSUE TITLE
Wrong audio-volume icons for elementary-xfce-dark theme

### ISSUE THREAD

**Issue by radioactiveman** [shimmerproject/elementary-xfce#90]
The volume icons should be white for the dark theme to be visible on dark panels.
Currently they are symlinks to the elementary-xfce directory.

Example:
```
$ file audio-volume-high.svg 
audio-volume-high.svg: symbolic link to ../../../elementary-xfce/panel/24/audio-volume-high.svg
```

Version: elementary-xfce-icons 0.7

**Comment by radioactiveman** [comment]
Xfce panel size: 24px

**Comment by ochosi** [comment]
This is a problem with monochrome icons which you can only properly fix with symbolic icons and as long as apps don't use that, we're in this mess.

Brief explanation: currently the contexts in which icons appear are ordered by size (which isn't always correct/right), so basically I say: everything that's bigger than 22px might not be a panel but something else, e.g. a button, so if I have a bright theme with a dark panel I need to make all icons <22px bright and all others dark or colored.

So unfortunately there is no real/general fix, only a workaround for you personally for your setup.

**Comment by radioactiveman** [comment]
Thanks for the explanation. For me still confusing is that bright icons are shown if the panel size is >= 27px. But I am using 24px and the 22px icons are bright. By the way, the 16px icons are dark. Is this on purpose?

**Comment by ochosi** [comment]
Yes, 16px is for menus.
