### ISSUE TITLE
tar.xz compressed files show up with generic icon  

### ISSUE THREAD

**Issue by fbrau** [shimmerproject/elementary-xfce#91]
Plain xz compressed and tar archive txz too.
they should be like the .gz icons

**Comment by ochosi** [comment]
Did you create the tarball yourself? If so, did you make sure to preserve the symlinks?

If you did that then I'm not sure I understand the bugreport - please elaborate! Thanks!

**Comment by fbrau** [comment]
I have .xz file that this theme shows as a generic icon
![captura de pantalla_2016-03-13_10-55-20](https://cloud.githubusercontent.com/assets/8375315/13729072/bf829412-e90a-11e5-9b96-96a0a5f883e4.png)

This is a tar.xz file and its icon is fine...
![captura de pantalla_2016-03-13_10-55-47](https://cloud.githubusercontent.com/assets/8375315/13729077/f561277e-e90a-11e5-89ce-faa8fcf63327.png)

The .xz icon should be the same as tar.xz file.

Even more, the tar.xz icon should say "tar.xz" as in
![captura de pantalla_2016-03-13_10-56-52](https://cloud.githubusercontent.com/assets/8375315/13729107/b0e07a90-e90b-11e5-8b13-b9cce655bdce.png)

**Comment by ochosi** [comment]
Not sure what the naming convention for .xz files is, is there a theme you know of where that filetype has the correct icon?

Also, whether the ending should be on the package is subjective and I'm not even a huge fan of that. A package is a package after all, not too much difference to really highlight that (plus it's a duplication of what you see in the filename ending anyway).

**Comment by fbrau** [comment]
XZ is a compression format, just as .zip, .gz or .rar 
the mimetype is "application/x-xz; charset=binary"

Maybe it doesn't sound at all for design guys (no offense, just a point) but
distros and new tools are using it more and more (packages mostly)
so it is no obscure format at all.

As for the big-package-format-label I understand what you mean, it is redundant,
but when you are viewing a directory with 1000 files and get an overview of 
what kind of archives are there with just a glance it is invaluable. And this,
I think is what makes this theme stand above all, true... maybe it is not the most cute or modern of all themes
but is almost complete and it *doesnt lie* using extremely cute icons in spite
of the  clarity.

I think it is fair to display the label because there is not one archive format but
many.
