### ISSUE TITLE
Source code files icons confuse (.h .c)

### ISSUE THREAD

**Issue by Yanpas** [shimmerproject/elementary-xfce#93]
Elementary lacks support of source code icons. `.h` and `.c` files share same icon. Don't you mind me adding letters C or H to the icons and creating PR?

Does this draft fits theme's phylosophy? (font **Ubuntu Mono Bold**)
![f](https://cloud.githubusercontent.com/assets/7345761/14412754/1b02651a-ff72-11e5-96b1-577044ea2baf.png)

**Comment by ochosi** [comment]
Actually .c and .h files have different icons, maybe you're referring to .cpp files?

Note that if you want to submit a pull request for that, I need the icon in all sizes (or: at least 16, 24, 32, 48, 64, 128) and it needs to be sharp and crisp in every size. Also, please use whatever font was used to create the .c and .h mimetype icons.
Thanks in advance!

**Comment by ochosi** [comment]
No response, closing.
