### ISSUE TITLE
Possibility of new release

### ISSUE THREAD

**Issue by hannes101** [shimmerproject/elementary-xfce#95]
I've just seen, that upstream released quite some updates and it would be great if we could get a new release, so that packages can be updated.

Thanks
johannes

**Comment by ochosi** [comment]
Sure, that can be done, but just to be clear: the syncing of icons from upstream is a manual process, so the state of the two icon themes is not really on par. So if you're hoping for specific icons that have been updated upstream, they may not yet have found their way here yet.
(Also: upstream elementary has more people working on the icon theme, I'm pretty much on my own here.)

**Comment by hannes101** [comment]
I didn't want to push you and I know how much work you do. I just thought syncing would be an automatic process, so I thought it's not much of a hassle. No problem to wait until you've find some time.

**Comment by NicoHood** [comment]
Why not create a normal github fork that you can update via simple pullup requests? Is there any problem with this?

**Comment by ochosi** [comment]
Release done (0.9).

**Comment by NicoHood** [comment]
@ochosi Could you please gpg sign the release?

**Comment by ochosi** [comment]
@NicoHood done.

**Comment by NicoHood** [comment]
@ochosi Thanks. But how did you sign the release? If you just downloaded it from github, signed it and uploaded the signature, it will not give any better security. You have to create a local tarball that you then sign and upload both. This is essential, as we need to ensure the source were not modified on transit to github, from github or on the github server itself.

You can use my tool gpgit if you wish. It helps you to accomplish all the required steps:
https://github.com/NicoHood/gpgit
