### ISSUE TITLE
Icons for xfce4-weather-plugin

### ISSUE THREAD

**Issue by teresaejunior** [shimmerproject/elementary-xfce#96]
It would be great if there was a theme for xfce4-weather-plugin that was similar to the panel icons. The default icon themes for the weather plugin are available on /usr/share/xfce4/weather/icons/, and there are more available on the web for download, but none that matches the look of the default panel icons for elementary Xfce darker!

Thank you for your attention!

**Comment by ochosi** [comment]
I have made two icon themes for the xfce4-weather-plugin already, one is "Simplistic" and the other is a port of "Faenza".
As elementary upstream doesn't have any weather icons and I neither have time nor energy to create a third theme I don't see this happening unless somebody else gets to it. Sorry.

**Comment by ochosi** [comment]
FWIW here's where they're maintained: https://github.com/ochosi/weather-icons

**Comment by teresaejunior** [comment]
Closing this as the new Clima icons fit perfectly with other monochrome icon themes: https://www.xfce-look.org/p/1165881/
