### ISSUE TITLE
Possibility of Availability in the Official Debian Repo?

### ISSUE THREAD

**Issue by tranjeeshan** [shimmerproject/elementary-xfce#99]
Hi,
I appreciate the work you're doing with Xubuntu, especially the Xfce in general. I've been a Xubuntu fan for its' usability and the aesthetics; but switched to Debian Xfce for some reasons. I was wondering if there's any chance of uploading the elementary-xfce icon themes in the official Debian repository, like you guys did with the greybird-gtk-theme? Thanks.

**Comment by ochosi** [comment]
Thanks, that's always nice to hear!
I'm not a Debian maintainer so it might be best to bring it up with one of them directly on the Debian issue tracker. I think it's standard procedure to file requests for packages there.

**Comment by tranjeeshan** [comment]
Will do. Thank you!

**Comment by ochosi** [comment]
Feel free to reopen if you need anything from my side for this.
